# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Amarjeet\Documents\GitHub\Interference\GUI\1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 600)
        MainWindow.setSizeIncrement(QtCore.QSize(5, 5))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(20, 50, 951, 491))
        self.main_frame.setMouseTracking(False)
        self.main_frame.setAcceptDrops(True)
        self.main_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.Slit_Option = QtWidgets.QComboBox(self.main_frame)
        self.Slit_Option.setGeometry(QtCore.QRect(430, 10, 191, 31))
        self.Slit_Option.setAutoFillBackground(True)
        self.Slit_Option.setEditable(False)
        self.Slit_Option.setObjectName("Slit_Option")
        self.Slit_Option.addItem("")
        self.Slit_Option.setItemText(0, "SINGLE SLIT")
        self.Slit_Option.addItem("")
        self.Slit_Option.addItem("")
        self.Slit_Option.addItem("")
        self.Slit_Option.addItem("")
        self.Slit_Option.addItem("")
        self.Distance = QtWidgets.QDoubleSpinBox(self.main_frame)
        self.Distance.setGeometry(QtCore.QRect(430, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        self.Distance.setFont(font)
        self.Distance.setAcceptDrops(True)
        self.Distance.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Distance.setMaximum(999.99)
        self.Distance.setSingleStep(0.5)
        self.Distance.setObjectName("Distance")
        self.Wavelength = QtWidgets.QDoubleSpinBox(self.main_frame)
        self.Wavelength.setGeometry(QtCore.QRect(430, 130, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(10)
        self.Wavelength.setFont(font)
        self.Wavelength.setAcceptDrops(True)
        self.Wavelength.setFrame(True)
        self.Wavelength.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Wavelength.setDecimals(3)
        self.Wavelength.setMaximum(999.99)
        self.Wavelength.setSingleStep(0.01)
        self.Wavelength.setObjectName("Wavelength")
        self.Slit_Option_label = QtWidgets.QLabel(self.main_frame)
        self.Slit_Option_label.setGeometry(QtCore.QRect(20, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Slit_Option_label.setFont(font)
        self.Slit_Option_label.setTextFormat(QtCore.Qt.PlainText)
        self.Slit_Option_label.setObjectName("Slit_Option_label")
        self.Distance_label = QtWidgets.QLabel(self.main_frame)
        self.Distance_label.setGeometry(QtCore.QRect(20, 70, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Distance_label.setFont(font)
        self.Distance_label.setTextFormat(QtCore.Qt.PlainText)
        self.Distance_label.setObjectName("Distance_label")
        self.Wavelength_label = QtWidgets.QLabel(self.main_frame)
        self.Wavelength_label.setGeometry(QtCore.QRect(20, 130, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Wavelength_label.setFont(font)
        self.Wavelength_label.setTextFormat(QtCore.Qt.PlainText)
        self.Wavelength_label.setObjectName("Wavelength_label")
        self.Distance.raise_()
        self.Wavelength.raise_()
        self.Slit_Option.raise_()
        self.Slit_Option_label.raise_()
        self.Distance_label.raise_()
        self.Wavelength_label.raise_()
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 951, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Slit_Option.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Slit_Option.setWhatsThis(_translate("MainWindow", "Slit Configuration"))
        self.Slit_Option.setItemText(1, _translate("MainWindow", "DOUBLE SLIT"))
        self.Slit_Option.setItemText(2, _translate("MainWindow", "DOUBLE POINT"))
        self.Slit_Option.setItemText(3, _translate("MainWindow", "MULTIPLE SLIT"))
        self.Slit_Option.setItemText(4, _translate("MainWindow", "MULTIPLE POINT"))
        self.Slit_Option.setItemText(5, _translate("MainWindow", "COUSTOMIZED SLIT"))
        self.Distance.setAccessibleName(_translate("MainWindow", "Distance"))
        self.Wavelength.setWhatsThis(_translate("MainWindow", "Wavelenght of light being used"))
        self.Wavelength.setAccessibleName(_translate("MainWindow", "Wavelength"))
        self.Wavelength.setAccessibleDescription(_translate("MainWindow", "Wavelenght of light being used"))
        self.Slit_Option_label.setText(_translate("MainWindow", "Slit Configuration :"))
        self.Distance_label.setText(_translate("MainWindow", "Distance Of the Screen from the slit :"))
        self.Wavelength_label.setText(_translate("MainWindow", "Wavelength of light being used :"))
        self.label_2.setText(_translate("MainWindow", "Hello! This is a program which gives you back a interference pattern on screen according to the slit that you provide."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

